name: Linter
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  Golint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run Golint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          args: "--tests=false"